export const TYPES = {
    GET_FUNKOS: "GET_FUNKOS",
    ADD_TO_CART: "ADD_TO_CART",
    SUM_IN_CART: "SUM_IN_CART",
    REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
    SEARCH_FUNKOS: "SEARCH_FUNKOS",
    CHANGE_TEXT_BUTTON: 'CHANGE_TEXT_BUTTON',
    GET_USER: 'GET_USER',
    CREATE_USER: "CREATE_USER",
    ORDER_FUNKOS: "ORDER_FUNKOS",
    GET_FUNKO_DETAIL: "GET_FUNKO_DETAIL",

    GET_CATEGORIES: "GET_CATEGORIES",
    GET_BRANDS: "GET_BRANDS",
    GET_LICENSE: "GET_LICENSE",
    
    HANDLE_CATEGORIES: "HANDLE_CATEGORIES",
    HANDLE_BRANDS: "HANDLE_BRANDS",
    HANDLE_LICENSE: "HANDLE_LICENSE",



}