export const TYPES = {
  GET_FUNKOS: "GET_FUNKOS",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_BRANDS: "GET_BRANDS",
  GET_LICENSE: "GET_LICENSE",

  HANDLE_CATEGORIES: "HANDLE_CATEGORIES",
  HANDLE_BRANDS: "HANDLE_BRANDS",
  HANDLE_LICENSE: "HANDLE_LICENSE",
  GET_REVIEWS: "GET_REVIEWS",

  ADD_TO_CART: "ADD_TO_CART",
  SUM_IN_CART: "SUM_IN_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  CLEAR_CART: "CLEAR_CART",

  SEARCH_FUNKOS: "SEARCH_FUNKOS",
  CHANGE_TEXT_BUTTON: "CHANGE_TEXT_BUTTON",

  GET_USER: "GET_USER",
  CREATE_USER: "CREATE_USER",
  FIND_USER: "FIND_USER",
  LOGOUT_USER: "LOGOUT_USER",

  ORDER_FUNKOS: "ORDER_FUNKOS",
  GET_FUNKO_DETAIL: "GET_FUNKO_DETAIL",

  MODIFIED_TOTAL: "MODIFIED_TOTAL",
  
  CHANGE_PAGE: "CHANGE_PAGE",

  CREATE_FUNKO: "CREATE_FUNKO",
  DELETE_FUNKO: "DELETE_FUNKO",
  MODIFY_FUNKO: "MODIFY_FUNKO",

  GET_CONFIRM: "GET_CONFIRM",

  RESET_PASSWORD: "RESET_PASSWORD",

  GET_ORDERS: "GET_ORDERS",
  CHANGE_STATUS: "CHANGE_STATUS",
  FILTER_STATUS: "FILTER_STATUS"
};
